// The bru shim (Addendum F, "How a CLI climb works"): a small Node script placed FIRST on PATH
// for a CLI-driven run's sandbox. It appends one `{ts, argv}` line to turns.jsonl for every
// invocation, then execs the REAL bru (resolved once, at write time -- so the shim never has to
// search PATH again at run time and can never accidentally exec itself) with the same argv, stdio
// inherited, and the same exit code. "Turns = shim lines" (Addendum F): this is the only thing
// that produces turns.jsonl.

import fs from 'node:fs';
import path from 'node:path';

// resolveRealBru(env) -- the same PATH search harness/sandbox.js's resolveBru does, duplicated
// (not imported) so this module has no dependency on sandbox.js's internals.
export function resolveRealBru(env = process.env) {
  const pathVar = env.PATH || '';
  const dirs = pathVar.split(path.delimiter).filter(Boolean);
  for (const dir of dirs) {
    const candidate = path.join(dir, 'bru');
    try {
      fs.accessSync(candidate, fs.constants.X_OK);
      return fs.realpathSync(candidate);
    } catch {
      // not here, keep looking
    }
  }
  throw new Error('bru is not installed (or not on PATH) -- cannot write the logging shim.');
}

// The generated shim is deliberately CommonJS: it is written to an extension-less file named
// literally `bru`, and Node picks module type for extension-less files by walking UP for the
// nearest package.json -- which, once this sits under an arbitrary runs/<model>/<seed>/<attempt>
// sandbox, could belong to this repo (type: module) or to nothing at all. Dropping a
// {"type":"commonjs"} package.json into binDir (writeBruShim, below) pins it unambiguously
// regardless of where the sandbox lives, so `require` here is always safe.
const SHIM_TEMPLATE = (realBruPath, turnsPath) => `#!/usr/bin/env node
// AUTO-GENERATED by src/harness/cli/shim.js -- do not edit by hand.
'use strict';
const { appendFileSync } = require('node:fs');
const { spawnSync } = require('node:child_process');

const argv = process.argv.slice(2);
try {
  appendFileSync(${JSON.stringify(turnsPath)}, JSON.stringify({ ts: Date.now(), argv }) + '\\n');
} catch (e) {
  // logging must never block the real command from running
}

const result = spawnSync(${JSON.stringify(realBruPath)}, argv, { stdio: 'inherit' });
if (result.error) {
  process.stderr.write('bru shim: ' + result.error.message + '\\n');
  process.exit(1);
}
process.exit(result.status === null ? 1 : result.status);
`;

// writeBruShim({binDir, turnsPath, realBruPath?}) -> {shimPath, realBruPath, turnsPath}
//
// Writes `<binDir>/bru` (mode 0o755) plus a `{"type":"commonjs"}` package.json next to it.
// `turnsPath` is wherever the harness wants turns.jsonl to live -- typically OUTSIDE the CLI's own
// writable sandbox root, so the agent can never edit its own turn count. `realBruPath` defaults to
// resolving the CALLER's (this process's) PATH; a test can pass a fixture path instead.
export function writeBruShim({ binDir, turnsPath, realBruPath } = {}) {
  if (!binDir) throw new Error('writeBruShim: binDir is required');
  if (!turnsPath) throw new Error('writeBruShim: turnsPath is required');
  const resolvedReal = realBruPath || resolveRealBru();
  fs.mkdirSync(binDir, { recursive: true });
  const resolvedTurnsPath = path.resolve(turnsPath);
  fs.writeFileSync(path.join(binDir, 'package.json'), '{"type":"commonjs"}\n');
  const shimPath = path.join(binDir, 'bru');
  fs.writeFileSync(shimPath, SHIM_TEMPLATE(resolvedReal, resolvedTurnsPath), { mode: 0o755 });
  return { shimPath, realBruPath: resolvedReal, turnsPath: resolvedTurnsPath };
}

// buildShimEnv(binDir, baseEnv = process.env) -> env object with `binDir` PREPENDED to PATH.
// "PATH keeps the original entries after it so the CLI's own runtime resolves" (Addendum F): the
// shim must win the `bru` lookup, but node/python/git/etc. the CLI itself needs must still resolve
// from the ORIGINAL PATH, so this only ever prepends, never replaces.
export function buildShimEnv(binDir, baseEnv = process.env) {
  return { ...baseEnv, PATH: `${binDir}${path.delimiter}${baseEnv.PATH || ''}` };
}

// readTurns(turnsPath) -> [{ts, argv}, ...] parsed from turns.jsonl; a missing file reads as no
// turns yet. Convenience for tests and for whatever drives the polling loop to compute `turns`
// ("Turns = shim lines", Addendum F).
export function readTurns(turnsPath) {
  let text;
  try {
    text = fs.readFileSync(turnsPath, 'utf8');
  } catch {
    return [];
  }
  return text
    .split('\n')
    .filter(Boolean)
    .map((line) => JSON.parse(line));
}
