// The full public route table, as pure data. Field names in request/response
// schemas are snake_case; spec.js is responsible for renaming them per
// world.naming and world.namingExceptions (via fieldName in world.js).
//
// Path templates use the vocab placeholders {workspaces}/{projects}/{assets}/
// {library} (resolved by world.resolvePath) plus one named placeholder per
// path param ({workspace_id}, {project_id}, {asset_id}, {job_id}, {n}), in the
// same order as that route's `params` entries.

const linkRef = (name) => ({ $ref: name });

const bearerTokenSchema = {
  type: 'object',
  properties: {
    access_token: { type: 'string' },
    token_type: { type: 'string', enum: ['bearer'] },
    expires_in: { type: 'integer' },
    refresh_token: { type: 'string' },
  },
  required: ['access_token', 'token_type', 'expires_in', 'refresh_token'],
};

const paginatedParams = [
  { name: 'cursor', in: 'query', type: 'string', required: false },
  { name: 'page_size', in: 'query', type: 'integer', required: false },
];

const idempotencyHeader = { name: 'Idempotency-Key', in: 'header', type: 'string', required: false };

export const routes = [
  {
    id: 'auth.token',
    method: 'POST',
    path: '/auth/token',
    summary: "Exchange an api key for a bearer token",
    params: [],
    requestSchema: {
      type: 'object',
      required: ['api_key'],
      properties: { api_key: { type: 'string' } },
    },
    responseSchema: bearerTokenSchema,
    behaviors: ['auth'],
    inSpec: true,
  },
  {
    id: 'auth.refresh',
    method: 'POST',
    path: '/auth/refresh',
    summary: 'Exchange a refresh token for a new bearer token',
    params: [],
    requestSchema: {
      type: 'object',
      required: ['refresh_token'],
      properties: { refresh_token: { type: 'string' } },
    },
    responseSchema: bearerTokenSchema,
    behaviors: ['auth'],
    inSpec: true,
  },
  {
    id: 'workspaces.list',
    method: 'GET',
    path: '/{workspaces}',
    summary: 'List workspaces',
    params: paginatedParams,
    responseSchema: {
      type: 'object',
      properties: {
        data: { type: 'array', items: linkRef('workspace') },
        cursor: { type: 'string' },
      },
      required: ['data'],
    },
    behaviors: ['pagination', 'rateLimit'],
    inSpec: true,
  },
  {
    id: 'workspaces.get',
    method: 'GET',
    path: '/{workspaces}/{workspace_id}',
    summary: 'Get one workspace, including a links block for lora library discovery',
    params: [{ name: 'workspace_id', in: 'path', type: 'string', required: true }],
    responseSchema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        name: { type: 'string' },
        created_at: { type: 'string' },
        links: { type: 'object' },
      },
      required: ['id', 'name', 'created_at', 'links'],
    },
    behaviors: ['discovery'],
    inSpec: true,
  },
  {
    id: 'projects.list',
    method: 'GET',
    path: '/{workspaces}/{workspace_id}/{projects}',
    summary: 'List projects in a workspace',
    params: [{ name: 'workspace_id', in: 'path', type: 'string', required: true }, ...paginatedParams],
    responseSchema: {
      type: 'object',
      properties: {
        data: { type: 'array', items: linkRef('project') },
        cursor: { type: 'string' },
      },
      required: ['data'],
    },
    behaviors: ['pagination', 'nestedResource'],
    inSpec: true,
  },
  {
    id: 'projects.create',
    method: 'POST',
    path: '/{workspaces}/{workspace_id}/{projects}',
    summary: 'Create a project in a workspace',
    params: [{ name: 'workspace_id', in: 'path', type: 'string', required: true }, idempotencyHeader],
    requestSchema: {
      type: 'object',
      required: ['name'],
      properties: { name: { type: 'string' } },
    },
    responseSchema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        name: { type: 'string' },
        status: { type: 'string', enum: ['draft', 'composed', 'rendered', 'published'] },
        created_at: { type: 'string' },
      },
      required: ['id', 'name', 'status', 'created_at'],
    },
    behaviors: ['idempotency', 'nestedResource'],
    inSpec: true,
  },
  {
    id: 'projects.get',
    method: 'GET',
    path: '/{workspaces}/{workspace_id}/{projects}/{project_id}',
    summary: 'Get one project and its state machine status',
    params: [
      { name: 'workspace_id', in: 'path', type: 'string', required: true },
      { name: 'project_id', in: 'path', type: 'string', required: true },
    ],
    responseSchema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        status: { type: 'string', enum: ['draft', 'composed', 'rendered', 'published'] },
        updated_at: { type: 'string' },
      },
      required: ['id', 'status', 'updated_at'],
    },
    behaviors: ['stateMachine', 'etag'],
    inSpec: true,
  },
  {
    id: 'projects.compose',
    method: 'POST',
    path: '/{workspaces}/{workspace_id}/{projects}/{project_id}/compose',
    summary: 'Compose a draft project; 409 unless status is draft',
    params: [
      { name: 'workspace_id', in: 'path', type: 'string', required: true },
      { name: 'project_id', in: 'path', type: 'string', required: true },
    ],
    requestSchema: { type: 'object', properties: { asset_ids: { type: 'array', items: { type: 'string' } } } },
    responseSchema: { type: 'object', properties: { id: { type: 'string' }, status: { type: 'string' } } },
    behaviors: ['stateMachine'],
    inSpec: true,
  },
  {
    id: 'projects.render',
    method: 'POST',
    path: '/{workspaces}/{workspace_id}/{projects}/{project_id}/render',
    summary: 'Kick off an async render; 409 unless composed, 202 + Location otherwise',
    params: [
      { name: 'workspace_id', in: 'path', type: 'string', required: true },
      { name: 'project_id', in: 'path', type: 'string', required: true },
    ],
    responseSchema: { type: 'object', properties: { job_id: { type: 'string' } } },
    behaviors: ['async', 'stateMachine'],
    inSpec: true,
  },
  {
    id: 'projects.publish',
    method: 'POST',
    path: '/{workspaces}/{workspace_id}/{projects}/{project_id}/publish',
    summary: 'Publish a rendered project; requires HMAC signing, 409 unless rendered',
    params: [
      { name: 'workspace_id', in: 'path', type: 'string', required: true },
      { name: 'project_id', in: 'path', type: 'string', required: true },
      { name: 'X-Timestamp', in: 'header', type: 'string', required: true },
      { name: 'X-Signature', in: 'header', type: 'string', required: true },
    ],
    responseSchema: { type: 'object', properties: { id: { type: 'string' }, status: { type: 'string' } } },
    behaviors: ['hmac', 'stateMachine'],
    inSpec: true,
  },
  {
    id: 'projects.assets',
    method: 'GET',
    path: '/{workspaces}/{workspace_id}/{projects}/{project_id}/{assets}',
    summary: 'List assets belonging to a project, JSON or CSV, soft-delete filterable',
    params: [
      { name: 'workspace_id', in: 'path', type: 'string', required: true },
      { name: 'project_id', in: 'path', type: 'string', required: true },
      { name: 'include_deleted', in: 'query', type: 'boolean', required: false },
      { name: 'Accept', in: 'header', type: 'string', required: false },
      ...paginatedParams,
    ],
    responseSchema: {
      type: 'object',
      properties: { data: { type: 'array', items: linkRef('asset') }, cursor: { type: 'string' } },
      required: ['data'],
    },
    behaviors: ['pagination', 'contentNegotiation', 'softDelete', 'nestedResource'],
    inSpec: true,
  },
  {
    id: 'images.create',
    method: 'POST',
    path: '/images',
    summary: 'Create an image asset from a descriptor',
    params: [idempotencyHeader],
    requestSchema: { type: 'object', required: ['width', 'height'], properties: { width: { type: 'integer' }, height: { type: 'integer' } } },
    responseSchema: {
      type: 'object',
      properties: { id: { type: 'string' }, descriptor: { type: 'object' }, hash: { type: 'string' }, etag: { type: 'string' } },
      required: ['id', 'descriptor', 'hash', 'etag'],
    },
    behaviors: ['idempotency'],
    inSpec: true,
  },
  {
    id: 'audio.create',
    method: 'POST',
    path: '/audio',
    summary: 'Create an audio asset from a descriptor',
    params: [idempotencyHeader],
    requestSchema: { type: 'object', required: ['notes'], properties: { notes: { type: 'array' } } },
    responseSchema: {
      type: 'object',
      properties: { id: { type: 'string' }, descriptor: { type: 'object' }, hash: { type: 'string' }, etag: { type: 'string' } },
      required: ['id', 'descriptor', 'hash', 'etag'],
    },
    behaviors: ['idempotency'],
    inSpec: true,
  },
  {
    id: 'video.create',
    method: 'POST',
    path: '/video',
    summary: 'Create a video asset from a timeline descriptor',
    params: [idempotencyHeader],
    requestSchema: { type: 'object', required: ['clips'], properties: { clips: { type: 'array' } } },
    responseSchema: {
      type: 'object',
      properties: { id: { type: 'string' }, descriptor: { type: 'object' }, hash: { type: 'string' }, etag: { type: 'string' } },
      required: ['id', 'descriptor', 'hash', 'etag'],
    },
    behaviors: ['idempotency'],
    inSpec: true,
  },
  {
    id: 'assets.get',
    method: 'GET',
    path: '/{assets}/{asset_id}',
    summary: 'Get an asset by id; supports If-None-Match',
    params: [
      { name: 'asset_id', in: 'path', type: 'string', required: true },
      { name: 'If-None-Match', in: 'header', type: 'string', required: false },
    ],
    responseSchema: { type: 'object', properties: { id: { type: 'string' }, descriptor: { type: 'object' }, hash: { type: 'string' } } },
    behaviors: ['etag', 'conditionalGet'],
    inSpec: true,
  },
  {
    id: 'assets.patch',
    method: 'PATCH',
    path: '/{assets}/{asset_id}',
    summary: 'Update asset metadata; requires If-Match, 412 on mismatch',
    params: [
      { name: 'asset_id', in: 'path', type: 'string', required: true },
      { name: 'If-Match', in: 'header', type: 'string', required: true },
    ],
    requestSchema: { type: 'object', properties: { display_name: { type: 'string' } } },
    responseSchema: { type: 'object', properties: { id: { type: 'string' }, display_name: { type: 'string' } } },
    behaviors: ['ifMatch'],
    inSpec: true,
  },
  {
    id: 'assets.delete',
    method: 'DELETE',
    path: '/{assets}/{asset_id}',
    summary: 'Soft delete an asset',
    params: [{ name: 'asset_id', in: 'path', type: 'string', required: true }],
    responseSchema: null,
    behaviors: ['softDelete', 'deleteStatus'],
    inSpec: true,
  },
  {
    id: 'assets.content',
    method: 'GET',
    path: '/{assets}/{asset_id}/content',
    summary: 'Get the raw artifact bytes for an asset',
    params: [{ name: 'asset_id', in: 'path', type: 'string', required: true }],
    responseSchema: null,
    behaviors: ['binary'],
    inSpec: true,
  },
  {
    id: 'assets.convert',
    method: 'POST',
    path: '/{assets}/{asset_id}/convert',
    summary: 'Convert an asset to a new format/size/rate, producing a new asset',
    params: [{ name: 'asset_id', in: 'path', type: 'string', required: true }],
    requestSchema: { type: 'object', properties: { format: { type: 'string' }, width: { type: 'integer' }, height: { type: 'integer' } } },
    responseSchema: { type: 'object', properties: { id: { type: 'string' }, descriptor: { type: 'object' }, hash: { type: 'string' } } },
    behaviors: [],
    inSpec: true,
  },
  {
    id: 'assets.combine',
    method: 'POST',
    path: '/{assets}/combine',
    summary: 'Combine multiple assets into a new asset',
    params: [],
    requestSchema: {
      type: 'object',
      required: ['ids', 'mode'],
      properties: {
        ids: { type: 'array', items: { type: 'string' } },
        mode: { type: 'string', enum: ['layer', 'mix', 'sequence'] },
        opacity_step: { type: 'number' },
      },
    },
    responseSchema: { type: 'object', properties: { id: { type: 'string' }, descriptor: { type: 'object' }, hash: { type: 'string' } } },
    behaviors: [],
    inSpec: true,
  },
  {
    id: 'assets.diff',
    method: 'POST',
    path: '/{assets}/diff',
    summary: 'Diff two assets into a new asset containing the delta',
    params: [],
    requestSchema: { type: 'object', required: ['a', 'b'], properties: { a: { type: 'string' }, b: { type: 'string' } } },
    responseSchema: { type: 'object', properties: { id: { type: 'string' }, descriptor: { type: 'object' }, hash: { type: 'string' } } },
    behaviors: [],
    inSpec: true,
  },
  {
    id: 'loras.list',
    method: 'GET',
    path: '/{library}',
    summary: 'List available loras, optionally filtered by name; discoverable only via links',
    params: [{ name: 'name', in: 'query', type: 'string', required: false }],
    responseSchema: { type: 'object', properties: { data: { type: 'array', items: linkRef('lora') } } },
    behaviors: ['discovery'],
    inSpec: false,
  },
  {
    id: 'assets.lora',
    method: 'POST',
    path: '/{assets}/{asset_id}/lora',
    summary: 'Apply a lora to an asset, producing a new asset',
    params: [{ name: 'asset_id', in: 'path', type: 'string', required: true }],
    requestSchema: { type: 'object', required: ['lora_id'], properties: { lora_id: { type: 'string' } } },
    responseSchema: { type: 'object', properties: { id: { type: 'string' }, descriptor: { type: 'object' }, hash: { type: 'string' } } },
    behaviors: [],
    inSpec: true,
  },
  {
    id: 'jobs.get',
    method: 'GET',
    path: '/jobs/{job_id}',
    summary: 'Poll a job; status advances queued -> running -> done deterministically',
    params: [{ name: 'job_id', in: 'path', type: 'string', required: true }],
    responseSchema: { type: 'object', properties: { id: { type: 'string' }, status: { type: 'string', enum: ['queued', 'running', 'done'] } } },
    behaviors: ['async'],
    inSpec: true,
  },
  {
    id: 'pictures.legacy',
    method: 'GET',
    path: '/v1/pictures',
    summary: 'Deprecated alias of /images; 301s to the new path',
    params: [],
    responseSchema: null,
    behaviors: ['deprecated'],
    inSpec: true,
  },
  {
    id: 'rungs.current',
    method: 'GET',
    path: '/rungs/current',
    summary: "Get the current rung's plain-language task text and its number",
    params: [],
    responseSchema: { type: 'object', properties: { n: { type: 'integer' }, text: { type: 'string' } } },
    behaviors: [],
    inSpec: true,
  },
  {
    id: 'rungs.submit',
    method: 'POST',
    path: '/rungs/{n}/submit',
    summary: 'Submit asset ids for the current rung; one submission per rung',
    params: [{ name: 'n', in: 'path', type: 'integer', required: true }],
    requestSchema: { type: 'object', required: ['assets'], properties: { assets: { type: 'array', items: { type: 'string' } } } },
    responseSchema: { type: 'object', properties: { pass: { type: 'boolean' }, rung: { type: 'integer' } } },
    behaviors: [],
    inSpec: true,
  },
];
